name: CI - Build & Test (Docker)

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t aceest-fitness:ci .

      - name: Run pytest inside the Docker image
        run: docker run --rm aceest-fitness:ci pytest